// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Po3vEORYVDXfX9VhKEFh0670pFHBe9E',
    appId: '1:939846511775:web:9e77b300fb7aeef04246aa',
    messagingSenderId: '939846511775',
    projectId: 'yam-diary',
    authDomain: 'yam-diary.firebaseapp.com',
    storageBucket: 'yam-diary.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD6nJnTcQVnLGcD-CtQ5WQAUxnd17P8eE',
    appId: '1:939846511775:android:bddcc5d0ffc0ad434246aa',
    messagingSenderId: '939846511775',
    projectId: 'yam-diary',
    storageBucket: 'yam-diary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1sBQXKMXdGwNTO8-z_xrZ7520dwmAhyw',
    appId: '1:939846511775:ios:63ce1aa9db997d5d4246aa',
    messagingSenderId: '939846511775',
    projectId: 'yam-diary',
    storageBucket: 'yam-diary.firebasestorage.app',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1sBQXKMXdGwNTO8-z_xrZ7520dwmAhyw',
    appId: '1:939846511775:ios:63ce1aa9db997d5d4246aa',
    messagingSenderId: '939846511775',
    projectId: 'yam-diary',
    storageBucket: 'yam-diary.firebasestorage.app',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4Po3vEORYVDXfX9VhKEFh0670pFHBe9E',
    appId: '1:939846511775:web:bd807c5fdd598f6e4246aa',
    messagingSenderId: '939846511775',
    projectId: 'yam-diary',
    authDomain: 'yam-diary.firebaseapp.com',
    storageBucket: 'yam-diary.firebasestorage.app',
  );

}